Prepare BFI-10
```{r}
BFI10<-left_join(filter(cleaned_survey_data, grepl("BFI",item)) %>% 
                   mutate(value=as.numeric(value)) %>% 
                   filter(!is.na(value)) %>% 
                   distinct(tagid,item,value,survey_name,.keep_all = FALSE) %>% 
                   spread(item,value),
                 redcap_cleaned %>%
                   filter(!is.na(dob),!is.na(sa_date)) %>%
                   dplyr::select(tagid, sa_date, sb_date, dob),by="tagid")

BFI10_Wave1<-left_join(BFI10,survey_date, by = c("tagid","survey_name")) %>% 
  distinct(tagid,survey_name,.keep_all = TRUE) %>%
  mutate(qualtrics_date=value) %>% 
  dplyr::select(-value) %>%
  mutate(survey_date=ifelse(survey_name=="TAG - Sess 1 - V4 - Current",sa_date,
                            ifelse(survey_name=="TAG - Sess 1 - V1",sa_date,
                                   ifelse(survey_name=="TAG - Sess 1 - V2",sa_date,
                                          ifelse(survey_name=="TAG - Sess 1 - V3",sa_date,
                                                 ifelse(survey_name=="Sensitive Q's for 042",sb_date,as.character(qualtrics_date)
                                                 )))))) %>%
  dplyr::select(-qualtrics_date,-sb_date,-sa_date,-dob) %>%
  distinct(tagid,survey_name,.keep_all = TRUE) %>%
  mutate(BFI_10_1=ifelse(BFI_10_1==1,5,
                         ifelse(BFI_10_1==2,4,
                                ifelse(BFI_10_1==3,3,
                                       ifelse(BFI_10_1==4,2,
                                              ifelse(BFI_10_1==5,1,
                                                     BFI_10_1))))),
         BFI_10_3=ifelse(BFI_10_3==1,5,
                         ifelse(BFI_10_3==2,4,
                                ifelse(BFI_10_3==3,3,
                                       ifelse(BFI_10_3==4,2,
                                              ifelse(BFI_10_3==5,1,
                                                     BFI_10_3))))),
         BFI_10_4=ifelse(BFI_10_4==1,5,
                         ifelse(BFI_10_4==2,4,
                                ifelse(BFI_10_4==3,3,
                                       ifelse(BFI_10_4==4,2,
                                              ifelse(BFI_10_4==5,1,
                                                     BFI_10_4))))),
         BFI_10_5=ifelse(BFI_10_5==1,5,
                         ifelse(BFI_10_5==2,4,
                                ifelse(BFI_10_5==3,3,
                                       ifelse(BFI_10_5==4,2,
                                              ifelse(BFI_10_5==5,1,
                                                     BFI_10_5))))),
         BFI_10_7=ifelse(BFI_10_7==1,5,
                         ifelse(BFI_10_7==2,4,
                                ifelse(BFI_10_7==3,3,
                                       ifelse(BFI_10_7==4,2,
                                              ifelse(BFI_10_7==5,1,
                                                     BFI_10_7)))))) %>%
  mutate(BFI10_extra_N=2,
         BFI10_extra_missing=rowSums(is.na(cbind(BFI_10_1,BFI_10_6))),
         BFI10_extra_missing_perc=100*(rowSums(is.na(cbind(BFI_10_1,BFI_10_6)))/2),
         BFI10_extra_total=rowSums(cbind(BFI_10_1,BFI_10_6), na.rm=F),
         BFI10_extra_mean=rowMeans(cbind(BFI_10_1,BFI_10_6), na.rm=T),
         BFI10_agree_N=2,
         BFI10_agree_missing=rowSums(is.na(cbind(BFI_10_2,BFI_10_7))),
         BFI10_agree_missing_perc=100*(rowSums(is.na(cbind(BFI_10_2,BFI_10_7)))/2),
         BFI10_agree_total=rowSums(cbind(BFI_10_2,BFI_10_7), na.rm=F),
         BFI10_agree_mean=rowMeans(cbind(BFI_10_2,BFI_10_7), na.rm=T),
         BFI10_consc_N=2,
         BFI10_consc_missing=rowSums(is.na(cbind(BFI_10_3,BFI_10_8))),
         BFI10_consc_missing_perc=100*(rowSums(is.na(cbind(BFI_10_3,BFI_10_8)))/2),
         BFI10_consc_total=rowSums(cbind(BFI_10_3,BFI_10_8), na.rm=F),
         BFI10_consc_mean=rowMeans(cbind(BFI_10_3,BFI_10_8), na.rm=T),
         BFI10_neuro_N=2,
         BFI10_neuro_missing=rowSums(is.na(cbind(BFI_10_4,BFI_10_9))),
         BFI10_neuro_missing_perc=100*(rowSums(is.na(cbind(BFI_10_4,BFI_10_9)))/2),
         BFI10_neuro_total=rowSums(cbind(BFI_10_4,BFI_10_9), na.rm=F),
         BFI10_neuro_mean=rowMeans(cbind(BFI_10_4,BFI_10_9), na.rm=T),
         BFI10_open_N=2,
         BFI10_open_missing=rowSums(is.na(cbind(BFI_10_5,BFI_10_10))),
         BFI10_open_missing_perc=100*(rowSums(is.na(cbind(BFI_10_5,BFI_10_10)))/2),
         BFI10_open_total=rowSums(cbind(BFI_10_5,BFI_10_10), na.rm=F),
         BFI10_open_mean=rowMeans(cbind(BFI_10_5,BFI_10_10), na.rm=T))

## Save it
BFI10_Wave1_outdf <- BFI10_Wave1 %>% filter(!grepl("W2|W3|W4|W5|W6",survey_name)) %>% filter(!grepl("TAG3|TAG4",tagid)) 
BFI10_Wave1_TAG2_outdf <- BFI10_Wave1 %>% filter(!grepl("W2|W3|W4|W5|W6",survey_name)) %>% filter(!grepl("TAG0|TAG1|TAG2",tagid))
write.csv(BFI10_Wave1_outdf, file = paste0(workdir,"Qualtrics_Output/Wave1/BFI10_Wave1.csv"))
write.csv(BFI10_Wave1_TAG2_outdf, file = paste0(workdir,"Qualtrics_Output/Wave1/BFI10_Wave1_TAG2.csv"))

BFI10_Wave2_outdf <- BFI10_Wave1 %>% filter(grepl("W2",survey_name)) %>% 
  filter(!grepl("TAG3|TAG4",tagid)) 
write.csv(BFI10_Wave2_outdf, file = paste0(workdir,"Qualtrics_Output/Wave2/BFI10_Wave2.csv"))

BFI10_Wave2_TAG2_outdf <- BFI10_Wave1 %>% filter(grepl("W2",survey_name)) %>% 
  filter(!grepl("TAG0|TAG1|TAG2",tagid))
write.csv(BFI10_Wave2_TAG2_outdf, file = paste0(workdir,"Qualtrics_Output/Wave2/BFI10_Wave2_TAG2.csv"))

BFI10_Wave3_outdf <- BFI10_Wave1 %>% filter(grepl("W3",survey_name)) %>% 
  filter(!grepl("TAG3|TAG4",tagid))  
write.csv(BFI10_Wave3_outdf, file = paste0(workdir,"Qualtrics_Output/Wave3/BFI10_Wave3.csv"))

BFI10_Wave3_TAG2_outdf <- BFI10_Wave1 %>% filter(grepl("W3",survey_name)) %>% 
  filter(!grepl("TAG0|TAG1|TAG2",tagid))
write.csv(BFI10_Wave3_TAG2_outdf, file = paste0(workdir,"Qualtrics_Output/Wave3/BFI10_Wave3_TAG2.csv"))

BFI10_Wave4_outdf <- BFI10_Wave1 %>% filter(grepl("W4",survey_name)) 
write.csv(BFI10_Wave4_outdf, file = paste0(workdir,"Qualtrics_Output/Wave4/BFI10_Wave4.csv"))

BFI10_Wave5_outdf <- BFI10_Wave1 %>% filter(grepl("W5",survey_name)) 
write.csv(BFI10_Wave5_outdf, file = paste0(workdir,"Qualtrics_Output/Wave5/BFI10_Wave5.csv"))

BFI10_Wave6_outdf <- BFI10_Wave1 %>% filter(grepl("W6",survey_name)) 
write.csv(BFI10_Wave6_outdf, file = paste0(workdir,"Qualtrics_Output/Wave6/BFI10_Wave6.csv"))
